### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [MohMah/android-notepad#12]
With the last release almost 5 years ago, and not much activity lately: do you still maintain this app, @MohMah?

**Comment by IzzySoft** [comment]
Hope you're still up and well, @MohMah – mind if I ask for an answer? No pressure, I'll accept a "no" as well, just want to be sure about the status…

**Comment by MohMah** [comment]
Hey @IzzySoft Sorry for late reply, unfortunately this is not maintained anymore

**Comment by IzzySoft** [comment]
Thanks for your reply – though it's not the one I hoped for :wink: May I suggest to archive the repository then? That would set it read-only (code remains available) but clearly tells the status.

Meanwhile, best wishes for your ongoing (and future) projects!
